version: "3.9"
services:
  postgres:
    image: postgres:16.1
    environment:
      POSTGRES_DB: "test"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: 'test'
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

